<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Optimize>true</Optimize><ServerGarbageCollection>false</ServerGarbageCollection><TieredPGO>false</TieredPGO></PropertyGroup>
  <ItemGroup><Compile Include="Program.fs" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../ROP/ROP.fsproj" /></ItemGroup>
</Project>
